routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');


    
});

Route::post('tenant',[App\Http\Controllers\TenantsController::class, 'store'])->name('tenants.save');

Route::group(['prefix' => 'manager/auth' , 'namespace' => '\App\Http\Controllers\Manager\Auth','as' => 'manager.'],function(){

    //login
    Route::get('/login','LoginController@showLoginForm')->name('show.login');
    Route::post('/login','LoginController@login')->name('login');
    Route::post('/logout','LoginController@logout')->name('logout');

    //Forgot Password Routes
    Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    //Reset Password Routes
    Route::get('/password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/password/reset','ResetPasswordController@reset')->name('password.update');

});


Route::group(['middleware' => 'auth:managers','prefix' => 'dashboard','namespace' => '\App\Http\Controllers\Manager','as' => 'manager.'],function(){
    Route::get('/','DashboardController@index')->name('dashboard');

});

app/Models/Manager.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Manager extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $guard = 'managers';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Tenant.php
<?php

namespace App\Models;

use Stancl\Tenancy\Database\Models\Tenant as BaseTenant;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;

class Tenant extends BaseTenant implements TenantWithDatabase
{
    use HasDatabase, HasDomains;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ImpersonatesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Stancl\Tenancy\Features\UserImpersonation;

class ImpersonatesController extends Controller
{
    

    public function index($token)
    {
        return UserImpersonation::makeResponse($token);
    }
}

app/Http/Controllers/Manager/DashboardController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    
    /**
     * Show Manager Dashboard.
     * 
     * @return \Illuminate\Http\Response
     */
    public function index(){
        return view('manager.dashboard');
    }
}

app/Http/Controllers/Tenant/DashboardController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    

    public function index()
    {
        return view('tenant.dashboard');
    }
}

app/Http/Controllers/TenantsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tenant;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class TenantsController extends Controller
{
    

    public function store()
    {
        $this->validate(request(),[
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'subdomain' => ['required','string','unique:domains,domain']        
        ]);
        
        $tenant = Tenant::create();

        $tenant->domains()->create([
            'domain' => request('subdomain'),
        ]);

        $user = '';
        $tenant->run(function() use(&$user){
            $user = User::create([
                'name' => request('name'),
                'email' => request('email'),
                'password' => Hash::make(request('password')),
            ]);
        });
        $redirectUrl = '/dashboard';
        $token = tenancy()->impersonate($tenant, $user->id, $redirectUrl);

        return redirect(tenant_route($tenant->domains()->first()->domain  . '.' . request()->getHttpHost(), 'impersonate',[
            'token' => $token
        ]));

    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/includes/footer.blade.php
<div class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between">
							<!--begin::Copyright-->
	<div class="text-dark order-2 order-md-1">
		<span class="text-muted font-weight-bold mr-2">2020©</span>
		<a href="#" target="_blank" class="text-dark-75 text-hover-primary">ahmedzahran</a>
	</div>
	<div class="nav nav-dark">
		<a href="#" target="_blank" class="nav-link pl-0 pr-5">About</a>
		<a href="#" target="_blank" class="nav-link pl-0 pr-5">Team</a>
		<a href="#" target="_blank" class="nav-link pl-0 pr-0">Contact</a>
	</div>
							<!--end::Nav-->
</div>

resources/views/includes/header.blade.php
<div id="kt_header" class="header header-fixed">
    <div class="container-fluid d-flex align-items-stretch justify-content-between">
        <div class="header-menu-wrapper header-menu-wrapper-left" id="kt_header_menu_wrapper">
            <div class="header-menu header-menu-mobile header-menu-layout-default" id="kt_header_menu">
            
                <ul class="menu-nav">
                    <li class="menu-item" aria-haspopup="true">
                        <a href="#" class="menu-link">
                            <i class="menu-icon flaticon-home"></i>
                        </a>
                    </li>
                    
                </ul>

            </div>
        </div>
        <!--begin::Topbar-->
        <div class="topbar">

            <div class="dropdown">
                <div class="topbar-item" data-toggle="dropdown" data-offset="10px,0px" aria-expanded="true">
                    <div class="btn btn-icon btn-clean btn-dropdown btn-lg mr-1">
                        <img class="h-20px w-20px rounded-sm" src="{{asset('images/logo.png')}}" alt="">
                    </div>
                    <span class="d-md-down-none">ahmed</span>
                </div>

                <div class="dropdown-menu p-0 m-0 dropdown-menu-anim-up dropdown-menu-sm dropdown-menu-right" style="">
                    <ul class="navi navi-hover py-4">
                        <li class="navi-item">
                            
                        </li>
                        @if(Auth::guard('web')->check())
                            <li class="navi-item">
                                <a class="navi-link" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </li>
                        @endif
                        @if(Auth::guard('managers')->check())
                            <li class="navi-item">
                                <a class="navi-link" href="{{ route('manager.logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('manager.logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </li>
                        @endif

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/includes/managerSidebar.blade.php
<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Tenants</span>
    </a>
</li>

<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Channels</span>
    </a>
</li>

<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Plans</span>
    </a>
</li>


<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Subscriptions</span>
    </a>
</li>

<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Invoices</span>
    </a>
</li>

<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Reports</span>
    </a>
</li>

<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Support</span>
    </a>
</li>

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Right Side Of Navbar -->
            
        </div>
    </div>
</nav>  

resources/views/includes/partials/messages.blade.php
@if($errors->any())
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        @foreach($errors->all() as $error)
            {{ $error }}<br/>
        @endforeach
    </div>
@elseif(session()->get('flash_success'))
{{--    <div class="alert alert-success" role="alert">--}}
{{--        <button type="button" class="close" data-dismiss="alert" aria-label="Close">--}}
{{--            <span aria-hidden="true">&times;</span>--}}
{{--        </button>--}}

{{--        @if(is_array(json_decode(session()->get('flash_success'), true)))--}}
{{--            {{ implode('', session()->get('flash_success')->all(':message<br/>')) }}--}}
{{--        @else--}}
{{--            {{ session()->get('flash_success') }}--}}
{{--        @endif--}}
{{--    </div>--}}
    @push('after-scripts')
    <script>
        Swal.fire({
            position: "top-right",
            icon: "success",
            title: '{{ is_array(json_decode(session()->get('flash_success'), true)) ? implode('', session()->get('flash_success')->all(':message<br/>')) : session()->get('flash_success') }}',
            showConfirmButton: false,
            timer: 1500
        });
    </script>
    @endpush

@elseif(session()->get('flash_warning'))
{{--    <div class="alert alert-warning" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        @if(is_array(json_decode(session()->get('flash_warning'), true)))
            {{ implode('', session()->get('flash_warning')->all(':message<br/>')) }}
        @else
            {{ session()->get('flash_warning') }}
        @endif

    </div>--}}
    @push('after-scripts')
        <script>
            Swal.fire({
                position: "top-right",
                icon: "warning",
                title: '{{ is_array(json_decode(session()->get('flash_warning'), true)) ? implode('', session()->get('flash_warning')->all(':message<br/>')) : session()->get('flash_warning') }}',
                showConfirmButton: false,
                timer: 1500
            });
        </script>
    @endpush

@elseif(session()->get('flash_info'))
{{--    <div class="alert alert-info" role="alert">--}}
{{--        <button type="button" class="close" data-dismiss="alert" aria-label="Close">--}}
{{--            <span aria-hidden="true">&times;</span>--}}
{{--        </button>--}}

{{--        @if(is_array(json_decode(session()->get('flash_info'), true)))--}}
{{--            {{ implode('', session()->get('flash_info')->all(':message<br/>')) }}--}}
{{--        @else--}}
{{--            {{ session()->get('flash_info') }}--}}
{{--        @endif--}}
{{--    </div>--}}

    @push('after-scripts')
        <script>
            Swal.fire({
                position: "top-right",
                icon: "info",
                title: '{{ is_array(json_decode(session()->get('flash_info'), true)) ? implode('', session()->get('flash_info')->all(':message<br/>')) : session()->get('flash_info') }}',
                showConfirmButton: false,
                timer: 1500
            });
        </script>
    @endpush

@elseif(session()->get('flash_danger'))
{{--    <div class="alert alert-danger" role="alert">--}}
{{--        <button type="button" class="close" data-dismiss="alert" aria-label="Close">--}}
{{--            <span aria-hidden="true">&times;</span>--}}
{{--        </button>--}}

{{--        @if(is_array(json_decode(session()->get('flash_danger'), true)))--}}
{{--            {{ implode('', session()->get('flash_danger')->all(':message<br/>')) }}--}}
{{--        @else--}}
{{--            {{ session()->get('flash_danger') }}--}}
{{--        @endif--}}
{{--    </div>--}}

    @push('after-scripts')
        <script>
            Swal.fire({
                position: "top-right",
                icon: "error",
                title: '{{ is_array(json_decode(session()->get('flash_danger'), true)) ? implode('', session()->get('flash_danger')->all(':message<br/>')) : session()->get('flash_danger') }}',
                showConfirmButton: false,
                timer: 1500
            });
        </script>
    @endpush

@elseif(session()->get('flash_message'))
{{--    <div class="alert alert-info" role="alert">--}}
{{--        <button type="button" class="close" data-dismiss="alert" aria-label="Close">--}}
{{--            <span aria-hidden="true">&times;</span>--}}
{{--        </button>--}}

{{--        @if(is_array(json_decode(session()->get('flash_message'), true)))--}}
{{--            {{ implode('', session()->get('flash_message')->all(':message<br/>')) }}--}}
{{--        @else--}}
{{--            {{ session()->get('flash_message') }}--}}
{{--        @endif--}}
{{--    </div>--}}

    @push('after-scripts')
        <script>
            Swal.fire({
                title: '{{ is_array(json_decode(session()->get('flash_message'), true)) ? implode('', session()->get('flash_message')->all(':message<br/>')) : session()->get('flash_message') }}',
                showConfirmButton: false,
                timer: 1500
            });
        </script>
    @endpush
@endif

resources/views/includes/sidebar.blade.php
<div class="brand flex-column-auto" id="kt_brand" kt-hidden-height="65" style="">
    <!--begin::Logo-->
    <a href="#" class="brand-logo">
        <img alt="Logo" width="60px" src="{{asset('images/logo.png')}}">
    </a>
    <!--end::Logo-->
    <!--begin::Toggle-->
    <button class="brand-toggle btn btn-sm px-0" id="kt_aside_toggle">
        <span class="svg-icon svg-icon svg-icon-xl">
        <!--begin::Svg Icon | path:assets/media/svg/icons/Navigation/Angle-double-left.svg-->
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <polygon points="0 0 24 0 24 24 0 24"></polygon>
            <path d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z" fill="#000000" fill-rule="nonzero" transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999)"></path>
            <path d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999)"></path>
            </g>
        </svg>
        <!--end::Svg Icon-->
    </span>
    </button>     <!--end::Toolbar-->
</div>

<!-- begain menu -->
<div class="aside-menu-wrapper flex-column-fluid" id="kt_aside_menu_wrapper">
                        <!--begin::Menu Container-->
    <div id="kt_aside_menu" class="aside-menu my-4 scroll ps ps--active-y" data-menu-vertical="1" data-menu-scroll="1" data-menu-dropdown-timeout="500" style="height: 263px; overflow: hidden;">
        <!--begin::Menu Nav-->
        <ul class="menu-nav">
            
            <li class="menu-item  menu-item-active" aria-haspopup="true">
                <a href="#" class="menu-link">
                    <i class="menu-icon flaticon-home"></i>
                    <span class="menu-text">dashboard</span>
                </a>
            </li>

            @if(Auth::guard('web')->check())
                @include('includes.tenantSidebar')
            @endif
            @if(Auth::guard('managers')->check())
                @include('includes.managerSidebar')
            @endif

        </ul>
        <!--end::Menu Nav-->
        <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; height: 263px; right: 4px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 49px;"></div></div></div>
        <!--end::Menu Container-->
</div>
<!-- end menu -->

resources/views/includes/tenantSidebar.blade.php
<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Users</span>
    </a>
</li>

<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Billing</span>
    </a>
</li>

<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">My Channels</span>
    </a>
</li>

<li class="menu-item" aria-haspopup="true">
    <a href="#" class="menu-link">
        <i class="menu-icon flaticon-map"></i>
        <span class="menu-text">Support</span>
    </a>
</li>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    <style>
        /* these styles will animate bootstrap alerts. */
        .alert{
            z-index: 99;
            top: 60px;
            right:18px;
            min-width:30%;
            position: fixed;
            animation: slide 0.5s forwards;
        }
        @keyframes slide {
            100% { top: 30px; }
        }
        @media screen and (max-width: 668px) {
            .alert{ /* center the alert on small screens */
                left: 10px;
                right: 10px; 
            }
        }
    </style>

    <title>{{config('app.name')}}</title>
</head>
<body>

    @include('includes.navbar')
    <main class="container mt-4">
        @yield('content')
    </main>

    <script src="{{mix('js/app.js')}}"></script>
    
    {{-- Success Alert --}}
    @if(session('status'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{session('status')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    {{-- Error Alert --}}
    @if(session('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{session('error')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <script>
        //close the alert after 3 seconds.
        $(document).ready(function(){
	    setTimeout(function() {
	        $(".alert").alert('close');
	    }, 3000);
    	});
    </script>
    
</body>
</html>

resources/views/layouts/tenant.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/manager/dashboard.blade.php
@extends('layouts.manager')

@section('title', 'dashboard')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tenant/dashboard.blade.php
@extends('layouts.manager')

@section('title', 'dashboard')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection